NAir = {
    AIR_WING_MAX_STATS_ATTACK = 1000,					-- Max stats
	AIR_WING_MAX_STATS_DEFENCE = 1000,
	AIR_WING_MAX_STATS_AGILITY = 1000,
	AIR_WING_MAX_STATS_SPEED = 8000,
	AIR_WING_MAX_STATS_BOMBING = 1000
}